-- Migration: Challenge Tags (viddie/gb-issues#49)
-- Pure additions, safe to run on an existing database.

-- ====== tag_category ======
CREATE TABLE tag_category
(
 "id"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 name        varchar(64) NOT NULL,
 description text NULL,
 sort        integer NOT NULL DEFAULT 0,
 color       text NULL,
 is_archived boolean NOT NULL DEFAULT false,
 CONSTRAINT tag_category_pkey PRIMARY KEY ( "id" )
);

-- ====== tag ======
CREATE TABLE tag
(
 "id"                 integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 category_id          integer NOT NULL,
 name                 varchar(64) NOT NULL,
 description          text NOT NULL,
 sort                 integer NOT NULL DEFAULT 0,
 is_common            boolean NOT NULL DEFAULT false,
 is_player_assignable boolean NOT NULL DEFAULT true,
 is_ordinal           boolean NOT NULL DEFAULT false,
 selection_mode       text NOT NULL DEFAULT 'single',
 CONSTRAINT tag_pkey PRIMARY KEY ( "id" ),
 CONSTRAINT tag_category_id_fkey FOREIGN KEY ( category_id ) REFERENCES tag_category ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT check_tag_selection_mode CHECK ( selection_mode IN ('single', 'multi', 'range') ),
 CONSTRAINT check_tag_range_ordinal CHECK ( selection_mode <> 'range' OR is_ordinal = true )
);
CREATE INDEX tag_category_id_idx ON tag ( category_id );

-- ====== tag_value ======
-- Every tag has at least one value. Tags without qualifiers have exactly one value with name = NULL.
CREATE TABLE tag_value
(
 "id"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 tag_id      integer NOT NULL,
 name        varchar(64) NULL,
 description text NULL,
 sort        integer NOT NULL DEFAULT 0,
 CONSTRAINT tag_value_pkey PRIMARY KEY ( "id" ),
 CONSTRAINT tag_value_tag_id_fkey FOREIGN KEY ( tag_id ) REFERENCES tag ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX tag_value_tag_id_idx ON tag_value ( tag_id );
CREATE UNIQUE INDEX tag_value_one_implicit ON tag_value ( tag_id ) WHERE name IS NULL;

-- ====== challenge_tag ======
-- One row = one player assigning one tag value to one challenge
CREATE TABLE challenge_tag
(
 "id"          integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 challenge_id  integer NOT NULL,
 player_id     integer NOT NULL,
 tag_value_id  integer NOT NULL,
 date_created  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT challenge_tag_pkey PRIMARY KEY ( "id" ),
 CONSTRAINT challenge_tag_unique UNIQUE ( challenge_id, player_id, tag_value_id ),
 CONSTRAINT challenge_tag_challenge_id_fkey FOREIGN KEY ( challenge_id ) REFERENCES challenge ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT challenge_tag_player_id_fkey FOREIGN KEY ( player_id ) REFERENCES player ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT challenge_tag_tag_value_id_fkey FOREIGN KEY ( tag_value_id ) REFERENCES tag_value ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX challenge_tag_value_idx ON challenge_tag ( tag_value_id, challenge_id, player_id );
CREATE INDEX challenge_tag_player_idx ON challenge_tag ( player_id );

