<?php

require_once('../api_bootstrap.inc.php');

// One-shot migration, safe to re-run:
//  1. Create the challenge tag tables + indices (if missing), add tag.short, add tag.selection_mode (single/multi)
//  2. Rename campaign.date_added / map.date_added to date_created (+ view columns)
//  3. Backfill date_created of challenges, maps and campaigns from their oldest submission
//  4. Backfill account.date_created from the player's oldest submission
//  5. Add account.restrictions (if missing)
//  6. Seed the default tag categories, tags and values (matched by name, only missing ones are created)
//
// Query params:
//  dry_run=true  -> run everything inside the transaction, then roll back
//  verbose=true  -> list every changed row

// Values are either a name, or [name, description]. Tags without values have no qualifiers.
const DEFAULT_TAG_CATEGORIES = [
  [
    'name' => 'Meta',
    'description' => 'Meta information of challenges beyond gameplay elements.',
    'color' => '#e81919',
    'tags' => [
      [
        'name' => 'Length',
        'short' => 'L',
        'description' => 'Approximate length of the challenge when going at moderate pace with at most short breaks.',
        'is_common' => true,
        'is_ordinal' => true,
        'values' => ['<3m', '3-10m', '10-30m', '30m-1h', '>1h'],
      ],
      [
        'name' => 'Difficulty',
        'short' => 'Diff',
        'description' => 'The peak difficulty of the challenge, in SJ+ scale.',
        'is_common' => true,
        'is_ordinal' => true,
        'values' => ['Beginner', 'Intermediate', 'Advanced', 'Expert', 'Grandmaster', 'GM+1', 'GM+2', 'GM+3'],
      ],
      [
        'name' => 'Decoration',
        'short' => 'Deco',
        'description' => 'How pretty do you find the map in the parts of the challenge?',
        'is_common' => true,
        'is_ordinal' => true,
        'values' => ['Meh', 'Ok', 'Nice', 'Van Gogh'],
      ],
    ],
  ],
  [
    'name' => 'Gameplay',
    'description' => 'Various gameplay elements or features that apply to the majority of the map.',
    'color' => '#0dee0d',
    'tags' => [
      [
        'name' => 'Dashes',
        'description' => 'Madeline be dashing (or not).',
        'short' => 'Dash',
        'is_ordinal' => true,
        'values' => ['0', '1', '2', '3+'],
      ],
      [
        'name' => 'Holdable',
        'short' => 'Hold',
        'description' => 'Madeline be grabbing stuff.',
        'selection_mode' => 'multi',
        'values' => [['Light', 'Like a Jellyfish'], ['Heavy', 'Like a Theo crystal'], 'Other'],
      ],
      [
        'name' => 'Precision',
        'description' => 'High levels of precision required relative to the difficulty of the challenge.',
      ],
      [
        'name' => 'Grab Button',
        'short' => 'Grab B.',
        'description' => 'The grab button triggers an additional action.',
        'selection_mode' => 'multi',
        'values' => [
          ['Hook', 'From Superfecta'],
          ['Gate Toggle', 'From Golden Alleyway'],
          ['Wattson', 'From Spark in the Machine'],
        ],
      ],
    ],
  ],
  [
    'name' => 'Entities',
    'description' => 'A couple of the most used entities in maps.',
    'color' => '#17baee',
    'tags' => [
      ['name' => 'Dream Blocks', 'description' => 'Any kind of dream block.'],
      ['name' => 'Cassette Blocks', 'description' => 'Any kind of cassette block.'],
      ['name' => 'Seekers', 'description' => 'These wonky lookin mfs.'],
    ],
  ],
  [
    'name' => 'Misc',
    'description' => "Various things that don't fit other categories.",
    'color' => '#AAAAAA',
    'tags' => [
      ['name' => 'Landmine', 'description' => '💥 (the challenge is way harder than it looks)'],
    ],
  ],
];

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
  die_json(405, 'Method Not Allowed');
}

$account = get_user_data();
check_access($account, false);
if (!is_admin($account)) {
  die_json(403, 'Not authorized');
}

header('Content-Type: text/plain');

$dry_run = isset($_REQUEST['dry_run']) && $_REQUEST['dry_run'] === 'true';
$verbose = isset($_REQUEST['verbose']) && $_REQUEST['verbose'] === 'true';

echo $dry_run ? "=== DRY RUN (all changes will be rolled back) ===\n\n" : "=== LIVE RUN ===\n\n";

migration_query($DB, "BEGIN");

//#region Step 1: Tag tables
echo "Step 1: Tag system tables\n";

$tag_statements = [
  "tag_category" => "CREATE TABLE IF NOT EXISTS tag_category
    (
     \"id\"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     name        varchar(64) NOT NULL,
     description text NULL,
     sort        integer NOT NULL DEFAULT 0,
     color       text NULL,
     is_archived boolean NOT NULL DEFAULT false,
     CONSTRAINT tag_category_pkey PRIMARY KEY ( \"id\" )
    )",
  "tag" => "CREATE TABLE IF NOT EXISTS tag
    (
     \"id\"                 integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     category_id          integer NOT NULL,
     name                 varchar(64) NOT NULL,
     short                varchar(64) NULL,
     description          text NOT NULL,
     sort                 integer NOT NULL DEFAULT 0,
     is_common            boolean NOT NULL DEFAULT false,
     is_player_assignable boolean NOT NULL DEFAULT true,
     is_ordinal           boolean NOT NULL DEFAULT false,
     selection_mode       text NOT NULL DEFAULT 'single',
     CONSTRAINT tag_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT tag_category_id_fkey FOREIGN KEY ( category_id ) REFERENCES tag_category ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT check_tag_selection_mode CHECK ( selection_mode IN ('single', 'multi') )
    )",
  "tag_category_id_idx" => "CREATE INDEX IF NOT EXISTS tag_category_id_idx ON tag ( category_id )",
  "tag_value" => "CREATE TABLE IF NOT EXISTS tag_value
    (
     \"id\"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     tag_id      integer NOT NULL,
     name        varchar(64) NULL,
     description text NULL,
     sort        integer NOT NULL DEFAULT 0,
     CONSTRAINT tag_value_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT tag_value_tag_id_fkey FOREIGN KEY ( tag_id ) REFERENCES tag ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE
    )",
  "tag_value_tag_id_idx" => "CREATE INDEX IF NOT EXISTS tag_value_tag_id_idx ON tag_value ( tag_id )",
  "tag_value_one_implicit" => "CREATE UNIQUE INDEX IF NOT EXISTS tag_value_one_implicit ON tag_value ( tag_id ) WHERE name IS NULL",
  "challenge_tag" => "CREATE TABLE IF NOT EXISTS challenge_tag
    (
     \"id\"          integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     challenge_id  integer NOT NULL,
     player_id     integer NOT NULL,
     tag_value_id  integer NOT NULL,
     date_created  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT challenge_tag_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT challenge_tag_unique UNIQUE ( challenge_id, player_id, tag_value_id ),
     CONSTRAINT challenge_tag_challenge_id_fkey FOREIGN KEY ( challenge_id ) REFERENCES challenge ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT challenge_tag_player_id_fkey FOREIGN KEY ( player_id ) REFERENCES player ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT challenge_tag_tag_value_id_fkey FOREIGN KEY ( tag_value_id ) REFERENCES tag_value ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE
    )",
  "challenge_tag_value_idx" => "CREATE INDEX IF NOT EXISTS challenge_tag_value_idx ON challenge_tag ( tag_value_id, challenge_id, player_id )",
  "challenge_tag_player_idx" => "CREATE INDEX IF NOT EXISTS challenge_tag_player_idx ON challenge_tag ( player_id )",
];

foreach ($tag_statements as $relation => $statement) {
  $existed = relation_exists($DB, $relation);
  migration_query($DB, $statement);
  echo $existed ? "  '$relation' already exists, skipped\n" : "  '$relation' created\n";
}

// Some versions of the tag table had no selection_mode column, early versions also had a 'range' mode
if (column_exists($DB, "tag", "selection_mode")) {
  echo "  tag.selection_mode already exists, skipped\n";
} else {
  migration_query($DB, "ALTER TABLE tag ADD COLUMN selection_mode text NOT NULL DEFAULT 'single'");
  echo "  Added tag.selection_mode\n";
}
$result = migration_query($DB, "UPDATE tag SET selection_mode = 'single' WHERE selection_mode NOT IN ('single', 'multi')");
echo "  Converted " . pg_affected_rows($result) . " tag(s) with an unsupported selection_mode to 'single'\n";
migration_query($DB, "ALTER TABLE tag DROP CONSTRAINT IF EXISTS check_tag_range_ordinal");
migration_query($DB, "ALTER TABLE tag DROP CONSTRAINT IF EXISTS check_tag_selection_mode");
migration_query($DB, "ALTER TABLE tag ADD CONSTRAINT check_tag_selection_mode CHECK ( selection_mode IN ('single', 'multi') )");
echo "  (Re-)created constraint check_tag_selection_mode\n";

if (column_exists($DB, "tag", "short")) {
  echo "  tag.short already exists, skipped\n";
} else {
  migration_query($DB, "ALTER TABLE tag ADD COLUMN short varchar(64) NULL");
  echo "  Added tag.short\n";
}
echo "\n";
//#endregion

//#region Step 2: Rename date_added -> date_created
echo "Step 2: Rename date_added -> date_created\n";

foreach (["campaign", "map"] as $table) {
  $has_old = column_exists($DB, $table, "date_added");
  $has_new = column_exists($DB, $table, "date_created");
  if ($has_old && !$has_new) {
    $table_esc = pg_escape_identifier($table);
    migration_query($DB, "ALTER TABLE $table_esc RENAME COLUMN date_added TO date_created");
    echo "  Renamed $table.date_added -> $table.date_created\n";
  } else if (!$has_old && $has_new) {
    echo "  $table.date_created already exists, skipped\n";
  } else {
    migration_fail($DB, "Unexpected state for table '$table' (date_added: " . ($has_old ? "yes" : "no") . ", date_created: " . ($has_new ? "yes" : "no") . ")");
  }
}

// Postgres updates the view definitions automatically on table column renames, only the output column aliases have to be renamed
$query = "SELECT c.table_name, c.column_name
  FROM information_schema.columns c
  JOIN information_schema.views v ON v.table_schema = c.table_schema AND v.table_name = c.table_name
  WHERE c.table_schema = 'public' AND c.column_name IN ('campaign_date_added', 'map_date_added', 'for_map_date_added')
  ORDER BY c.table_name, c.column_name";
$result = migration_query($DB, $query);
$view_renames = 0;
while ($row = pg_fetch_assoc($result)) {
  $view = $row['table_name'];
  $old_column = $row['column_name'];
  $new_column = str_replace("date_added", "date_created", $old_column);
  $view_esc = pg_escape_identifier($view);
  $old_esc = pg_escape_identifier($old_column);
  $new_esc = pg_escape_identifier($new_column);
  migration_query($DB, "ALTER VIEW $view_esc RENAME COLUMN $old_esc TO $new_esc");
  echo "  Renamed view column $view.$old_column -> $view.$new_column\n";
  $view_renames++;
}
if ($view_renames === 0) {
  echo "  No view columns to rename, skipped\n";
}
echo "\n";
//#endregion

//#region Step 3: Backfill challenge/map/campaign creation dates
echo "Step 3: Backfill date_created from the oldest submission\n";

$query = "UPDATE challenge
  SET date_created = s.oldest_date
  FROM (
    SELECT challenge.id, challenge.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM challenge
    JOIN submission ON submission.challenge_id = challenge.id
    GROUP BY challenge.id
  ) s
  WHERE challenge.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (challenge.date_created IS NULL OR s.oldest_date < challenge.date_created)
  RETURNING challenge.id, s.old_date, s.oldest_date";
print_date_updates("challenge", migration_query($DB, $query), $verbose);

$query = "UPDATE map
  SET date_created = s.oldest_date
  FROM (
    SELECT map.id, map.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM map
    JOIN challenge ON challenge.map_id = map.id
    JOIN submission ON submission.challenge_id = challenge.id
    GROUP BY map.id
  ) s
  WHERE map.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (map.date_created IS NULL OR s.oldest_date < map.date_created)
  RETURNING map.id, s.old_date, s.oldest_date";
print_date_updates("map", migration_query($DB, $query), $verbose);

// Campaign challenges are either full game challenges (challenge.campaign_id) or challenges of the campaign's maps
$query = "UPDATE campaign
  SET date_created = s.oldest_date
  FROM (
    SELECT campaign.id, campaign.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM campaign
    JOIN (
      SELECT challenge.id AS challenge_id, COALESCE(challenge.campaign_id, map.campaign_id) AS campaign_id
      FROM challenge
      LEFT JOIN map ON challenge.map_id = map.id
    ) cc ON cc.campaign_id = campaign.id
    JOIN submission ON submission.challenge_id = cc.challenge_id
    GROUP BY campaign.id
  ) s
  WHERE campaign.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (campaign.date_created IS NULL OR s.oldest_date < campaign.date_created)
  RETURNING campaign.id, s.old_date, s.oldest_date";
print_date_updates("campaign", migration_query($DB, $query), $verbose);
echo "\n";
//#endregion

//#region Step 4: Backfill account creation dates
echo "Step 4: Backfill account.date_created from the player's oldest submission\n";

$query = "UPDATE account
  SET date_created = s.oldest_date
  FROM (
    SELECT account.id, account.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM account
    JOIN submission ON submission.player_id = account.player_id
    GROUP BY account.id
  ) s
  WHERE account.id = s.id
    AND s.oldest_date IS NOT NULL
    AND s.oldest_date < account.date_created
  RETURNING account.id, s.old_date, s.oldest_date";
print_date_updates("account", migration_query($DB, $query), $verbose);
echo "\n";
//#endregion

//#region Step 5: Account restrictions
echo "Step 5: Account restrictions\n";

if (column_exists($DB, "account", "restrictions")) {
  echo "  account.restrictions already exists, skipped\n";
} else {
  migration_query($DB, "ALTER TABLE account ADD COLUMN restrictions integer NOT NULL DEFAULT 0");
  echo "  Added account.restrictions\n";
}
echo "\n";
//#endregion

//#region Step 6: Default tags
echo "Step 6: Default tag categories, tags and values\n";

foreach (DEFAULT_TAG_CATEGORIES as $category_sort => $category_def) {
  $result = migration_query($DB, "SELECT id FROM tag_category WHERE LOWER(name) = LOWER($1) ORDER BY id LIMIT 1", [$category_def['name']]);
  if (pg_num_rows($result) > 0) {
    $category_id = intval(pg_fetch_result($result, 0, 0));
    echo "  Category '{$category_def['name']}' already exists, skipped\n";
  } else {
    $result = migration_query(
      $DB,
      "INSERT INTO tag_category (name, description, sort, color) VALUES ($1, $2, $3, $4) RETURNING id",
      [$category_def['name'], $category_def['description'], $category_sort, $category_def['color']]
    );
    $category_id = intval(pg_fetch_result($result, 0, 0));
    echo "  Created category '{$category_def['name']}'\n";
  }

  foreach ($category_def['tags'] as $tag_sort => $tag_def) {
    $result = migration_query(
      $DB,
      "SELECT id FROM tag WHERE category_id = $1 AND LOWER(name) = LOWER($2) LIMIT 1",
      [$category_id, $tag_def['name']]
    );
    if (pg_num_rows($result) > 0) {
      echo "    Tag '{$tag_def['name']}' already exists, skipped\n";
      continue;
    }

    $result = migration_query(
      $DB,
      "INSERT INTO tag (category_id, name, short, description, sort, is_common, is_player_assignable, is_ordinal, selection_mode)
        VALUES ($1, $2, $3, $4, $5, $6, true, $7, $8) RETURNING id",
      [
        $category_id,
        $tag_def['name'],
        $tag_def['short'] ?? null,
        $tag_def['description'],
        $tag_sort,
        ($tag_def['is_common'] ?? false) ? 't' : 'f',
        ($tag_def['is_ordinal'] ?? false) ? 't' : 'f',
        $tag_def['selection_mode'] ?? 'single',
      ]
    );
    $tag_id = intval(pg_fetch_result($result, 0, 0));

    // Tags without qualifiers get their single implicit value (name = NULL)
    $values = $tag_def['values'] ?? [[null, null]];
    foreach ($values as $value_sort => $value_def) {
      [$value_name, $value_description] = is_array($value_def) ? $value_def : [$value_def, null];
      migration_query(
        $DB,
        "INSERT INTO tag_value (tag_id, name, description, sort) VALUES ($1, $2, $3, $4)",
        [$tag_id, $value_name, $value_description, $value_sort]
      );
    }
    $value_names = isset($tag_def['values']) ? implode(', ', array_map(fn($v) => is_array($v) ? $v[0] : $v, $values)) : '<implicit>';
    echo "    Created tag '{$tag_def['name']}' [{$value_names}]\n";
  }
}
echo "\n";
//#endregion

if ($dry_run) {
  migration_query($DB, "ROLLBACK");
  echo "Dry run finished, all changes rolled back.\n";
} else {
  migration_query($DB, "COMMIT");
  echo "All changes committed.\n";
}


//#region Utility functions
function migration_fail($DB, string $message)
{
  pg_query($DB, "ROLLBACK");
  echo "\nERROR: $message\nAll changes rolled back.\n";
  exit();
}

function migration_query($DB, string $query, array $params = [])
{
  $result = pg_query_params($DB, $query, $params);
  if ($result === false) {
    migration_fail($DB, pg_last_error($DB));
  }
  return $result;
}

function relation_exists($DB, string $name): bool
{
  $result = migration_query($DB, "SELECT to_regclass($1) IS NOT NULL AS exists", ["public." . $name]);
  return pg_fetch_assoc($result)['exists'] === 't';
}

function column_exists($DB, string $table, string $column): bool
{
  $query = "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2";
  $result = migration_query($DB, $query, [$table, $column]);
  return pg_num_rows($result) > 0;
}

function print_date_updates(string $type, $result, bool $verbose)
{
  $count = pg_num_rows($result);
  echo "  Updated date_created of $count {$type}(s)\n";
  if (!$verbose) {
    return;
  }
  while ($row = pg_fetch_assoc($result)) {
    $old = $row['old_date'] ?? "NULL";
    echo "    $type #{$row['id']}: $old -> {$row['oldest_date']}\n";
  }
}
//#endregion
