<?php

require_once('../api_bootstrap.inc.php');

// One-shot migration, safe to re-run:
//  1. Create the challenge tag tables + indices (if missing)
//  2. Rename campaign.date_added / map.date_added to date_created (+ view columns)
//  3. Backfill date_created of challenges, maps and campaigns from their oldest submission
//  4. Backfill account.date_created from the player's oldest submission
//
// Query params:
//  dry_run=true  -> run everything inside the transaction, then roll back
//  verbose=true  -> list every changed row

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
  die_json(405, 'Method Not Allowed');
}

$account = get_user_data();
check_access($account, false);
if (!is_admin($account)) {
  die_json(403, 'Not authorized');
}

header('Content-Type: text/plain');

$dry_run = isset($_REQUEST['dry_run']) && $_REQUEST['dry_run'] === 'true';
$verbose = isset($_REQUEST['verbose']) && $_REQUEST['verbose'] === 'true';

echo $dry_run ? "=== DRY RUN (all changes will be rolled back) ===\n\n" : "=== LIVE RUN ===\n\n";

migration_query($DB, "BEGIN");

//#region Step 1: Tag tables
echo "Step 1: Tag system tables\n";

$tag_statements = [
  "tag_category" => "CREATE TABLE IF NOT EXISTS tag_category
    (
     \"id\"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     name        varchar(64) NOT NULL,
     description text NULL,
     sort        integer NOT NULL DEFAULT 0,
     color       text NULL,
     is_archived boolean NOT NULL DEFAULT false,
     CONSTRAINT tag_category_pkey PRIMARY KEY ( \"id\" )
    )",
  "tag" => "CREATE TABLE IF NOT EXISTS tag
    (
     \"id\"                 integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     category_id          integer NOT NULL,
     name                 varchar(64) NOT NULL,
     description          text NOT NULL,
     sort                 integer NOT NULL DEFAULT 0,
     is_common            boolean NOT NULL DEFAULT false,
     is_player_assignable boolean NOT NULL DEFAULT true,
     is_ordinal           boolean NOT NULL DEFAULT false,
     selection_mode       text NOT NULL DEFAULT 'single',
     CONSTRAINT tag_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT tag_category_id_fkey FOREIGN KEY ( category_id ) REFERENCES tag_category ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT check_tag_selection_mode CHECK ( selection_mode IN ('single', 'multi', 'range') ),
     CONSTRAINT check_tag_range_ordinal CHECK ( selection_mode <> 'range' OR is_ordinal = true )
    )",
  "tag_category_id_idx" => "CREATE INDEX IF NOT EXISTS tag_category_id_idx ON tag ( category_id )",
  "tag_value" => "CREATE TABLE IF NOT EXISTS tag_value
    (
     \"id\"        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     tag_id      integer NOT NULL,
     name        varchar(64) NULL,
     description text NULL,
     sort        integer NOT NULL DEFAULT 0,
     CONSTRAINT tag_value_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT tag_value_tag_id_fkey FOREIGN KEY ( tag_id ) REFERENCES tag ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE
    )",
  "tag_value_tag_id_idx" => "CREATE INDEX IF NOT EXISTS tag_value_tag_id_idx ON tag_value ( tag_id )",
  "tag_value_one_implicit" => "CREATE UNIQUE INDEX IF NOT EXISTS tag_value_one_implicit ON tag_value ( tag_id ) WHERE name IS NULL",
  "challenge_tag" => "CREATE TABLE IF NOT EXISTS challenge_tag
    (
     \"id\"          integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     challenge_id  integer NOT NULL,
     player_id     integer NOT NULL,
     tag_value_id  integer NOT NULL,
     date_created  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT challenge_tag_pkey PRIMARY KEY ( \"id\" ),
     CONSTRAINT challenge_tag_unique UNIQUE ( challenge_id, player_id, tag_value_id ),
     CONSTRAINT challenge_tag_challenge_id_fkey FOREIGN KEY ( challenge_id ) REFERENCES challenge ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT challenge_tag_player_id_fkey FOREIGN KEY ( player_id ) REFERENCES player ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE,
     CONSTRAINT challenge_tag_tag_value_id_fkey FOREIGN KEY ( tag_value_id ) REFERENCES tag_value ( \"id\" ) ON DELETE CASCADE ON UPDATE CASCADE
    )",
  "challenge_tag_value_idx" => "CREATE INDEX IF NOT EXISTS challenge_tag_value_idx ON challenge_tag ( tag_value_id, challenge_id, player_id )",
  "challenge_tag_player_idx" => "CREATE INDEX IF NOT EXISTS challenge_tag_player_idx ON challenge_tag ( player_id )",
];

foreach ($tag_statements as $relation => $statement) {
  $existed = relation_exists($DB, $relation);
  migration_query($DB, $statement);
  echo $existed ? "  '$relation' already exists, skipped\n" : "  '$relation' created\n";
}
echo "\n";
//#endregion

//#region Step 2: Rename date_added -> date_created
echo "Step 2: Rename date_added -> date_created\n";

foreach (["campaign", "map"] as $table) {
  $has_old = column_exists($DB, $table, "date_added");
  $has_new = column_exists($DB, $table, "date_created");
  if ($has_old && !$has_new) {
    $table_esc = pg_escape_identifier($table);
    migration_query($DB, "ALTER TABLE $table_esc RENAME COLUMN date_added TO date_created");
    echo "  Renamed $table.date_added -> $table.date_created\n";
  } else if (!$has_old && $has_new) {
    echo "  $table.date_created already exists, skipped\n";
  } else {
    migration_fail($DB, "Unexpected state for table '$table' (date_added: " . ($has_old ? "yes" : "no") . ", date_created: " . ($has_new ? "yes" : "no") . ")");
  }
}

// Postgres updates the view definitions automatically on table column renames, only the output column aliases have to be renamed
$query = "SELECT c.table_name, c.column_name
  FROM information_schema.columns c
  JOIN information_schema.views v ON v.table_schema = c.table_schema AND v.table_name = c.table_name
  WHERE c.table_schema = 'public' AND c.column_name IN ('campaign_date_added', 'map_date_added', 'for_map_date_added')
  ORDER BY c.table_name, c.column_name";
$result = migration_query($DB, $query);
$view_renames = 0;
while ($row = pg_fetch_assoc($result)) {
  $view = $row['table_name'];
  $old_column = $row['column_name'];
  $new_column = str_replace("date_added", "date_created", $old_column);
  $view_esc = pg_escape_identifier($view);
  $old_esc = pg_escape_identifier($old_column);
  $new_esc = pg_escape_identifier($new_column);
  migration_query($DB, "ALTER VIEW $view_esc RENAME COLUMN $old_esc TO $new_esc");
  echo "  Renamed view column $view.$old_column -> $view.$new_column\n";
  $view_renames++;
}
if ($view_renames === 0) {
  echo "  No view columns to rename, skipped\n";
}
echo "\n";
//#endregion

//#region Step 3: Backfill challenge/map/campaign creation dates
echo "Step 3: Backfill date_created from the oldest submission\n";

$query = "UPDATE challenge
  SET date_created = s.oldest_date
  FROM (
    SELECT challenge.id, challenge.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM challenge
    JOIN submission ON submission.challenge_id = challenge.id
    GROUP BY challenge.id
  ) s
  WHERE challenge.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (challenge.date_created IS NULL OR s.oldest_date < challenge.date_created)
  RETURNING challenge.id, s.old_date, s.oldest_date";
print_date_updates("challenge", migration_query($DB, $query), $verbose);

$query = "UPDATE map
  SET date_created = s.oldest_date
  FROM (
    SELECT map.id, map.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM map
    JOIN challenge ON challenge.map_id = map.id
    JOIN submission ON submission.challenge_id = challenge.id
    GROUP BY map.id
  ) s
  WHERE map.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (map.date_created IS NULL OR s.oldest_date < map.date_created)
  RETURNING map.id, s.old_date, s.oldest_date";
print_date_updates("map", migration_query($DB, $query), $verbose);

// Campaign challenges are either full game challenges (challenge.campaign_id) or challenges of the campaign's maps
$query = "UPDATE campaign
  SET date_created = s.oldest_date
  FROM (
    SELECT campaign.id, campaign.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM campaign
    JOIN (
      SELECT challenge.id AS challenge_id, COALESCE(challenge.campaign_id, map.campaign_id) AS campaign_id
      FROM challenge
      LEFT JOIN map ON challenge.map_id = map.id
    ) cc ON cc.campaign_id = campaign.id
    JOIN submission ON submission.challenge_id = cc.challenge_id
    GROUP BY campaign.id
  ) s
  WHERE campaign.id = s.id
    AND s.oldest_date IS NOT NULL
    AND (campaign.date_created IS NULL OR s.oldest_date < campaign.date_created)
  RETURNING campaign.id, s.old_date, s.oldest_date";
print_date_updates("campaign", migration_query($DB, $query), $verbose);
echo "\n";
//#endregion

//#region Step 4: Backfill account creation dates
echo "Step 4: Backfill account.date_created from the player's oldest submission\n";

$query = "UPDATE account
  SET date_created = s.oldest_date
  FROM (
    SELECT account.id, account.date_created AS old_date, MIN(submission.date_created) AS oldest_date
    FROM account
    JOIN submission ON submission.player_id = account.player_id
    GROUP BY account.id
  ) s
  WHERE account.id = s.id
    AND s.oldest_date IS NOT NULL
    AND s.oldest_date < account.date_created
  RETURNING account.id, s.old_date, s.oldest_date";
print_date_updates("account", migration_query($DB, $query), $verbose);
echo "\n";
//#endregion

if ($dry_run) {
  migration_query($DB, "ROLLBACK");
  echo "Dry run finished, all changes rolled back.\n";
} else {
  migration_query($DB, "COMMIT");
  echo "All changes committed.\n";
}


//#region Utility functions
function migration_fail($DB, string $message)
{
  pg_query($DB, "ROLLBACK");
  echo "\nERROR: $message\nAll changes rolled back.\n";
  exit();
}

function migration_query($DB, string $query, array $params = [])
{
  $result = pg_query_params($DB, $query, $params);
  if ($result === false) {
    migration_fail($DB, pg_last_error($DB));
  }
  return $result;
}

function relation_exists($DB, string $name): bool
{
  $result = migration_query($DB, "SELECT to_regclass($1) IS NOT NULL AS exists", ["public." . $name]);
  return pg_fetch_assoc($result)['exists'] === 't';
}

function column_exists($DB, string $table, string $column): bool
{
  $query = "SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2";
  $result = migration_query($DB, $query, [$table, $column]);
  return pg_num_rows($result) > 0;
}

function print_date_updates(string $type, $result, bool $verbose)
{
  $count = pg_num_rows($result);
  echo "  Updated date_created of $count {$type}(s)\n";
  if (!$verbose) {
    return;
  }
  while ($row = pg_fetch_assoc($result)) {
    $old = $row['old_date'] ?? "NULL";
    echo "    $type #{$row['id']}: $old -> {$row['oldest_date']}\n";
  }
}
//#endregion
